### PR TITLE
#25 Added git clean functionality

### PR DESCRIPTION
**Pull request by chaomix**
Adds git clean functionality as requested by #25. However, it only supports the basic git clean -f functionality. I feel like it would have been a large issue if I had included support for other options such as -d -x -X -ffd etc.

There was no simple 'git clean' function in NodeGit so it manually deletes untracked files by using git status and removing files (via fs) with the "NEW" status.

The function is located to the right of the pull button with a sweep icon and in the navbar when the app's size becomes small. I have included two images, one for the dark theme and the other for the light theme. Only the one for the dark theme (Clean-Dark.svg) is being used at the moment.

If no repository is selected and git clean is clicked, it will prompt the user to first open a repository. It also shows the user how many files were deleted upon success. 

When git clean deletes the files, it is not reflected in the file panel but is removed in the local directory. I believe it is most likely related to issue #60

### CODE REVIEW

**Review by Mehdi-Shah — APPROVED** [review]
Looks good

**Comment by softeng-701** [comment]
@chaomix please squash your commits

**Comment by chaomix** [comment]
@softeng-701 ready for merge. Squashed commits & merged with upstream/master

**Review by daedae-k — COMMENTED** [review]
Code looks good, and functionality is great!

**Pull request merged**
