### PR TITLE
Change name of repositories that were cloned from GitHub

### LINKED ISSUE #6: Change naming of repos cloned from GitHub
When you clone a repository from GitHub, the local folder which is created is named after the author’s name rather than the project’s name. This is especially a problem if you want to clone two repositories from the same author, as this will cause an error.

### PR DESCRIPTION
**Pull request by EmilyYVChan**
**UPDATE: Please refer to the updated details of the changes made in this PR in the latest few comments**
Closes #6 .

Before, the cloned repositories were named after the user's GitHub username. This prevents the user from cloning multiple repositories as they would be cloned to a directory of the same name. 

This bug was due to the variable 'localPath' storing the username, which was used to define the full directory address to which the repository is cloned to.

Changes made:
- extract the repository's name from the clone URL.
- append the extracted name to the full local directory path address
- update the appropriate label in the header bar to show the correct repository name
- for the git command shown to the user, remove the optional directory option. This is to ensure that the git command shown matches the git command executed.

### CODE REVIEW

**Comment by softeng-701** [comment]
@EmilyYVChan Please squash your commits

**Review by cli727 — CHANGES_REQUESTED** [review]
The header bar changes to corresponding repository name, however, when a different repository is opened, the header bar still displays the old repository name.

How I found the bug:

1. Open a local repository
2. Clone and open a different local repository

The repository name does not update in step 2.

**Comment by EmilyYVChan** [comment]
Thank you @cli727 ! The bug you found made me realise my assumptions were wrong and prompted me to rethink of my solution altogether. I initially assumed that the username was ALWAYS used as the folder name under which the repo is cloned. Turns out that when you clone a repo in the 'clone/open a repo' window it works perfectly fine. The bug was only when you try to clone in the main window by clicking the "repository" button in the header bar.

I have fixed the bug now. :) Kindly review then tag the TA.

**Comment by EmilyYVChan** [comment]
**UPDATED details of the changes made in this PR**
Closes #6 .

The user can clone repositories directly from the main window by clicking on the 'repository' button in the header bar and then selecting the desired repository to clone. The bug was that the cloned repository was named after the user's GitHub username instead of the repository name. This prevents the user from cloning multiple repositories directly from the main window as they would be cloned to a directory of the same name. 

This bug was due to the wrong part of the URL being extracted, as it was extracting the GitHub username instead of the repository name. This part of the URL was then used to define the local file path to which the repository is cloned. 

Changes made:
- extract the repository name from the correct part of the clone URL
- refactor error messages to provide more useful info for troubleshooting when failed to clone URL
- include safety mechanism in case the repository name could not be defined from the clone URL

**Review by cli727 — APPROVED** [review]

**Comment by EmilyYVChan** [comment]
@softeng-701 ready for merge :)

**Comment by softeng-701** [comment]
@EmilyYVChan please squash your commits

**Comment by softeng-701** [comment]
@EmilyYVChan Please resolve merge conflicts

**Comment by EmilyYVChan** [comment]
@softeng-701 Resolved :) (the conflict was simply a single empty line)

**Pull request merged**
