### PR TITLE
Closes Issue #115 - Opening existing repositories and repositories already cloned

### PR DESCRIPTION
**Pull request by SN4KE-EYES**
Allows the full path of an existing local repository to be used to open the local repository.

Files changed:
- repo.js
- repo.ts

Resolves: #115

### CODE REVIEW

**Comment by SN4KE-EYES** [comment]
@softeng-701 @kblincoe I am in a group by myself so I was wondering if one of you could review my request

**Review by kblincoe — APPROVED** [review]

**Comment by softeng-701** [comment]
@RSGWA I'm having trouble logging into visualgit on your branch and the master, are you seeing this issue?

**Comment by SN4KE-EYES** [comment]
@kblincoe Yeah, I was experiencing that issue as soon as I had forked and cloned the main repo. I didn't change any file that would effect it though, so I had no idea what the problem was

**Comment by softeng-701** [comment]
@RSGWA Seems to be a general issue introduced by another PR

**Comment by SN4KE-EYES** [comment]
@kblincoe Oh ok. So I'm good to merge?

**Comment by softeng-701** [comment]
@RSGWA Yes, we will merge after the deadline. (don't merge yourself. Thanks!)

**Comment by SN4KE-EYES** [comment]
@softeng-701 Cheers!

**Pull request merged**
