### PR TITLE
Fixes Issue #144 - Clone repository functionality is not working in case of cloning using URL

### PR DESCRIPTION
**Pull request by Madhusudansarma**
Clone repository functionality is not working in case of cloning using URL #144

### CODE REVIEW

**Review by karthiksriramuoa — APPROVED** [review]
Approved

**Review by cielluo — CHANGES_REQUESTED** [review]
Cannot start VisualGit after applying the changes. 
Please check the brace in the file "add.repository.component.js", and be more careful next time when you resolve conflicts.

**Review by cielluo — APPROVED** [review]

**Review by karthiksriramuoa — APPROVED** [review]
Approved

**Comment by cielluo** [comment]
The code looks fine now.
But I think the clone process is still wired now and needs further improving. I'll post this as a new issue.

**Comment by softeng-701** [comment]
@Madhusudansarma Please squash your commit before the deadline

**Pull request closed without merging**
