### PR TITLE
Fixed #3 - Move color setting to menu bar

### LINKED ISSUE #3: Move colour settings to menu bar
Colour settings can only be changed from the top left corner of the login screen. This setting would be better placed in the menu bar for easy access anywhere in the app.

### PR DESCRIPTION
**Pull request by cielluo**
Color settings are moved to menu bar and named 'Style' now.

Resolves: #3
See also: #80

### CODE REVIEW

**Comment by cielluo** [comment]
@softeng-701 @karthiksriramuoa

**Comment by softeng-701** [comment]
@ls-morning It's up to your group mates to review your PR, thanks!

**Review by karthiksriramuoa — APPROVED** [review]
Approved.

**Comment by cielluo** [comment]
@softeng-701 Approved and conflicts resolved, ready to merge

**Comment by softeng-701** [comment]
@ls-morning please squash your commits

**Comment by cielluo** [comment]
Closed due to squashing issues. Between my changes there are several PRs from others.
Created new branch with changes and another pull request.

**Pull request closed without merging**
