### PR TITLE
Warnings Implementation

### PR DESCRIPTION
**Pull request by LeightonJonker**
Edit: Addresses Issue #29 

The product of adding warnings to VisualGit in the case of users wanting to Exit / Sign Out / Pull if there are commits that have not been commited and if the repository has not been pushed.

Added option to reload

As opposed to only exiting the application when prompted; added the feature of allowing users to choose between reloading or exiting application, along with a back button.

Commit after Revert; grammar / commenting changed

Ready for another pull request after fixing up all previous errors and reverting failed pull request.

### CODE REVIEW

**Review by chaomix — APPROVED** [review]
Looks good bro

**Comment by softeng-701** [comment]
@LeightonJonker Which issue does this address? thanks

**Review by daedae-k — APPROVED** [review]
Good quality! Want to see this go live.

**Comment by LeightonJonker** [comment]
@softeng-701 Edited to say it solves issue #29 
Additionally, squashed commits

Thanks

**Pull request merged**
