### PR TITLE
Closes issue #28 Improved Security

### PR DESCRIPTION
**Pull request by sahilcc7**
This PR closes issue #28 (Improve Security) and #75 (Password displayed in tooltip). 

Usernames and passwords are now encrypted (AES) and not stored as plaintext in global variables. Getters and setters are used to authenticate with the nodegit API as well as remember login details. Commit tooltips now display the author properly due to the poor storage of credentials throughout the application.

Files changed: 

- app/misc/authenticate.js
-  app/misc/authenticate.ts
- app/misc/git.js
-  app/misc/git.ts
- app/misc/graphing.js
- app/misc/graphing.ts
- app/misc/readCredentials.js
- app/misc/readCredentials.ts
- app/misc/storeCredentials.js
- app/misc/storeCredentials.ts

### CODE REVIEW

**Review by Mehdi-Shah — APPROVED** [review]
Works fine

**Review by kzy618 — APPROVED** [review]
works fine

**Comment by sahilcc7** [comment]
@softeng-701 Ready for merging.

**Comment by softeng-701** [comment]
@sahilcc7 Looks good! will merge after the deadline

**Pull request merged**
