### PR TITLE
Closes issue #76 - Fixes graph after compile

### PR DESCRIPTION
**Pull request by sahilcc7**
The graph showing revision history now works after compiling all .ts files.
Regarding issue #76 
Files changed: 

- index.html
- repo.js
- repo.ts

### CODE REVIEW

**Review by Mehdi-Shah — APPROVED** [review]
Approved

**Comment by softeng-701** [comment]
@sahilcc7 Please have all group members review the PR, thanks!

**Review by kzy618 — APPROVED** [review]
works fine.

**Comment by softeng-701** [comment]
@sahilcc7 Looks good!

**Comment by softeng-701** [comment]
@sahilcc7 This PR is for a closed issue, was it closed before a PR resolved it?

**Comment by sahilcc7** [comment]
@softeng-701 Sorry I accidentally closed the issues before the pull request was merged in. I have reopened the issue. Cheers

**Pull request merged**
