### PR TITLE
Add create new GitHub account functionality

### PR DESCRIPTION
**Pull request by Mehdi-Shah**
Closes issue #125 

Files changed: 
 - authenticate.component.ts
 - authenticate.component.js

### CODE REVIEW

**Review by sahilcc7 — APPROVED** [review]
Looks all-good.

**Comment by softeng-701** [comment]
@Mehdi-Shah Please have all group members review the PR and resolve merge conflicts

**Review by kzy618 — APPROVED** [review]
working fine

**Comment by sahilcc7** [comment]
@softeng-701 Ready for merging.

**Comment by softeng-701** [comment]
@Mehdi-Shah @sahilcc7 Looks good, all further merging will be done after the deadline

**Pull request merged**
