### PR TITLE
Fixed the branch button so it shows the correct pointer on hover

### PR DESCRIPTION
**Pull request by ponchotang**
Closes issue #11 
When hovering over the branch button at the top of the screen, the mouse pointer will now change to the clicking hand rather than the text pointer.

### CODE REVIEW

**Review by shiny-eel — APPROVED** [review]
Approved. Possibly unnecessary changes to the Javascript generated file.

**Comment by ponchotang** [comment]
@softeng-701 please take a look at the .js file that was generated out of my changes and see if it's ok.

**Comment by softeng-701** [comment]
@ponchotang are you worried about the .js file causing issues? Its best to have your group review your changes

**Comment by ponchotang** [comment]
@softeng-701 It's just that the generated .js file seems to have moved some of the lines around and added/removed some parts that don't seem to be related to the actual change. Me and my group are inclined to believe it won't be an issue since it's compiled directly from the .ts file (which is where I made the changes) but I just wanted to confirm it with you.

**Comment by softeng-701** [comment]
@ponchotang do you notice any unexpected changes in the GUI after your change? Its up to you and your group to ok the PR.

**Comment by ponchotang** [comment]
@softeng-701 no, everything looks fine. Please merge the PR.

**Pull request merged**
