### PR TITLE
Created three scripts one bash and two batch for ubuntu and mac

### PR DESCRIPTION
**Pull request by shoebilldev**
run.desktop runs the "npm start" command on ubuntu machines and will show up as a Visual Git executable

run-bash-mac.command runs the "npm start" command on mac machines

run-batch.bat runs the "npm start" command in the windows cmd

The user may need to run once
"chmod u+x run-bash.sh" on ubuntu or 
"chmod +x run-bash-mac.command" on mac or run the 
"run-batch.bat" as admin depending on user privileges

closes issue #12

### CODE REVIEW

**Review by kathrynjaggar — APPROVED** [review]

**Review by DanyonW — APPROVED** [review]

**Review by kathrynjaggar — CHANGES_REQUESTED** [review]
This is not currently working for me, if I run the script from terminal it works, but it isn't clickable.

**Comment by softeng-701** [comment]
@tagumi changes have been requested

**Comment by softeng-701** [comment]
@tagumi Please look at the requested changes and squash your commits

**Comment by shoebilldev** [comment]
Changes have been made as per request

**Review by kathrynjaggar — APPROVED** [review]

**Comment by shoebilldev** [comment]
@softeng-701 ok to merge pr and close issue #58 ?

**Comment by softeng-701** [comment]
@tagumi You must squash your commits locally first, do you know how to do this?

**Comment by shoebilldev** [comment]
@softeng-701 yes, though I was just going to merge with this option:

image

will squash locally first though

**Comment by softeng-701** [comment]
@tagumi Please don't merge your own PR, it is against the specified workflow for this assignment. We would like squashes to be done locally so you get experience with the rebase command, thanks!

**Comment by shoebilldev** [comment]
Closed and Deleted due to rebasing issues, created new branch with changes and pull request for them.

Lessons were learned.

**Pull request closed without merging**
