### PR TITLE
Display github account name

### PR DESCRIPTION
**Pull request by Long315**
On the main screen, the gitHubName will be displayed on the right top of the screen, just next to 'log out' button.

### CODE REVIEW

**Review by sguy016 — APPROVED** [review]

**Review by sguy016 — CHANGES_REQUESTED** [review]
On the sign in screen, the sign in button on the top rignt corner is hided

**Review by sguy016 — APPROVED** [review]

**Comment by softeng-701** [comment]
@Long315 Please squash you commits and resolve merge conflicts. What is the number of the issue this resolves?

**Comment by Long315** [comment]
The conflicts have been resolved. Ready to merge now.
Issue 8: Display GitHub account name #8 @softeng-701

**Comment by Long315** [comment]
Oh, it seems that I made a mistake. I just want to squash my commits, but I clicked the "squash and merge" button by mistake.....Sorry to do your job @softeng-701, need I  create a new pull request to revert these changes?

**Comment by softeng-701** [comment]
@Long315 yes, its against the workflow for this assignment to merge your own PR.
I've made  a PR to revert: https://github.com/kblincoe/VisualGit_SE701_3/pull/84 
Please can you do the official review on the revert and then resubmit your PR. Thanks

**Pull request merged**
