### PR TITLE
Closes Issue#39, App now has fetch functionality via a button on the app bar

### PR DESCRIPTION
**Pull request by nathangavin**
Closes issue #39.

Changes made to the app include adding a 'sync' button to the top of the screen. when this button is pressed, the user is presented with a dialog which asks the user for the URL of the original repository they wish to sync. Then the app runs the various commands to establish the local remote repository, then pulling and merging from there, Also, the user is informed when the synchronization process as begun and has finished.

files edited:
 - app/components/header.component.ts
- app/misc/git.ts

files added:
- assets/refresh-button.png

### CODE REVIEW

**Review by Scoobster — CHANGES_REQUESTED** [review]
It looks like you are removing all generated javascript files from the repo. Please make it so they are unchanged.

**Review by Scoobster — APPROVED** [review]
Tested on my local machine and is working well! Code is well documented and looks to be bug free.

**Comment by Scoobster** [comment]
@softeng-701 tagging for approval and merge

**Comment by softeng-701** [comment]
@nathangavin @Scoobster Please squash your commits before the deadline. Also, make sure all group members have given their reviews. Thanks!

**Comment by softeng-701** [comment]
Looks good! Will merge after the deadline

**Comment by nathangavin** [comment]
@softeng-701  commits have been squashed, though doing the squash required a merge, creating a new commit. All group members have approved the code.

**Pull request merged**
