### PR TITLE
Closes Issue#130, can now log in using either email or username at both locations.

### PR DESCRIPTION
**Pull request by nathangavin**
Closes issue #130.

Changes made to the App include changing the placeholder text in the username section of both the main login screen and the inline login screen in the top right of the app. the functionality of the app allowed for users to use either their GitHub username or associated email address to log in. Now both log in places' reflect this functionality, with the placeholder text stating "Username or Email" at both places. Also, the username input area for the inline login screen has been made wider, to more comfortably accommodate email addresses, if the user wishes to use one.

files changed:
 - app/components/header.component.ts
 - app/components/authenticate.component.ts

### CODE REVIEW

**Review by Scoobster — CHANGES_REQUESTED** [review]
All javascript files have been removed. Please fix this

**Review by Scoobster — APPROVED** [review]
Tested on local machine and works perfectly. Code looks good :)

**Comment by Scoobster** [comment]
@softeng-701 tagging for approval and merge

**Comment by softeng-701** [comment]
@nathangavin @Scoobster Please squash your commits before the deadline. Also, make sure all group members have given their reviews. Thanks

**Comment by nathangavin** [comment]
@softeng-701 Commits have been squashed, but for some reason the old commits are still showing. All group members have approved the code.

**Comment by softeng-701** [comment]
@nathangavin We have been asked to merge PR's with 1 or 2 commits, right now you still have 31. If you have time please look at this

**Comment by nathangavin** [comment]
@softeng-701 for some reason the commits will not squash together. I used the same technique i had before, but its simply not registering.

**Comment by softeng-701** [comment]
@nathangavin This is a pretty small change, perhaps make a new branch off master and copy your changes into that. Then submit a new PR. Up to you. Cheers

**Comment by nathangavin** [comment]
@softeng-701 running the command "git rebase -i HEAD~10" tries to rebase 82 commits, instead of the 10 i request. 
capture

**Comment by nathangavin** [comment]
created a new pull request for this issue.

**Comment by softeng-701** [comment]
@nathangavin So we can close this one?

**Pull request closed without merging**
