### PR TITLE
New pull request - Clone repository functionality is not working in case of cloning using URL #144

### PR DESCRIPTION
**Pull request by Madhusudansarma**
Total Change of Files - 2
- add.repository.component.ts
- add.repository.component.js

I tried squashing my commits using "git rebase -i HEAD~3" from Kelly's Cloned Repository, but since it did not give me the exact commit history log, I closed my previous pull request and I am creating a new one for the same issue. 

Closes - #144

### CODE REVIEW

**Review by cielluo — APPROVED** [review]
Bugs are fixed in the last PR. LGTM.

**Comment by softeng-701** [comment]
@Madhusudansarma Please squash your commits and get all group members to review

**Review by karthiksriramuoa — APPROVED** [review]
Changes Approved

**Comment by karthiksriramuoa** [comment]
@softeng-701 He just from the university after he created the pull request. Have informed him to squash his commits. If is not able to do this by midnight, can he do this tomorrow?

**Comment by softeng-701** [comment]
@Madhusudansarma @karthiksriramuoa sorry I don't know the specifics, but I'd assume work done after the deadline will be treated differently when marking

**Comment by softeng-701** [comment]
@Madhusudansarma Please resolve the conflicts. Thanks!

**Comment by karthiksriramuoa** [comment]
@softeng-701 Resolving conflicts on behalf of Madhusudhan Sarma since he is not currently in town.

**Pull request merged**
