### PR TITLE
Closes Issue#20 - File browser added to open and clone repo

### PR DESCRIPTION
**Pull request by Scoobster**
This pull request is for closing the Issue #20 - Add file explorer to opening and closing

Functionality Added:
- Now if the user presses the "Open" button and text box for the directory is left blank, a file browser is launched to for the user to select a repository.
- If the text box for the save location under clone is left blank, when the user presses the "Clone" button, the file browser is launched for the user to select a folder.

Files changed:
- app/components/add.repository.component.js
- app/components/add.repository.component.ts
- app/misc/repo.js 
- app/misc/repo.ts

### CODE REVIEW

**Review by nathangavin — APPROVED** [review]
reviewed all code. cannot see any errors.

**Comment by Scoobster** [comment]
Tagging @softeng-701 for approval and merge

**Comment by softeng-701** [comment]
@Scoobster please squash your commits

**Comment by Scoobster** [comment]
@softeng-701 and @kblincoe now ready for approval and merging again.

I have squashed my commits which created the new commit f06e6d0 (the old commits still appear but Kelly said that was okay, as they don't appear in SourceTree - could be a GitHub issue). I resolved merge conflicts but was unable to squash it as the all the commits on Kelly's master appeared when attempting to squash so was told by Kelly not to squash.

**Review by nathangavin — COMMENTED** [review]
It looks good, I cannot find any errors with the changes.

**Pull request merged**
