### PR TITLE
Fixed - Move colour setting to menu bar #3

### PR DESCRIPTION
**Pull request by cielluo**
Currently users are able to find colour setting in menu bar so they can access the functionality anywhere in the application.
Also updated to suppert additional colour schemes.

Resolves: #3
See Also: #80, #19

### CODE REVIEW

**Comment by cielluo** [comment]
@karthiksriramuoa

**Review by karthiksriramuoa — APPROVED** [review]
Coffee review approved.

**Comment by cielluo** [comment]
@softeng-701 Ready to merge :-)

**Comment by softeng-701** [comment]
@ls-morning please have all group members review the PR, thanks!

**Review by Madhusudansarma — APPROVED** [review]
reviewed

**Pull request merged**
