### PR TITLE
Fixed mouse pointer when hovering add repo/push/pull buttons

### PR DESCRIPTION
**Pull request by ponchotang**
Closes issue #14 
This fix now changes the mouse pointer icon to the hand clicker when hovering over the symbols for adding a repo, push, and pull buttons.
This fix was done by adding 'a' tags with a href attribute to each of the relevant elements.

### CODE REVIEW

**Review by shiny-eel — APPROVED** [review]
Menubar buttons now correctly change cursor icon. (Y)

**Comment by ponchotang** [comment]
@softeng-701 requesting merge :)

**Comment by softeng-701** [comment]
@ponchotang Please squash your commits :)

**Comment by ponchotang** [comment]
@softeng-701 commits squashed.

**Pull request merged**
