### PR TITLE
Implemented VisualGit logo

### PR DESCRIPTION
**Pull request by Mehdi-Shah**
Closes issue #126 , the VisualGit program now has its own unique icon rather than the electron icon.

Files changed:
 - Index.js
 - Added VisualGit_Logo.png to assets folder

### CODE REVIEW

**Review by sahilcc7 — APPROVED** [review]
Looks good

**Comment by softeng-701** [comment]
@Mehdi-Shah Please have all group members review the PR

**Comment by kzy618** [comment]
it works fine

**Review by kzy618 — APPROVED** [review]
have proper logo design and iteration. looks good for me

**Comment by softeng-701** [comment]
@Mehdi-Shah Looks good

**Comment by softeng-701** [comment]
@Mehdi-Shah This PR is for a closed issue, was it closed early?

**Comment by sahilcc7** [comment]
@softeng-701 Sorry I accidentally closed the issues before the pull request was merged in. I have reopened the issue. Cheers

**Pull request merged**
