### PR TITLE
Add functionality for forgotten password

### LINKED ISSUE #30: Forgot password link
Add a forgotten password option to the login and main screen, which links back to GitHub online forgotten password system.

### PR DESCRIPTION
**Pull request by EmilyYVChan**
Closes #30 

Changes made:
At the login screen, the user can click on the "Forgot your password?" link, which opens a modal internet-browser dialog showing the GitHub's online forgotten password system webpage for the user to interact with.

### CODE REVIEW

**Review by cli727 — COMMENTED** [review]
Looks good! Just a minor suggestion to move the code in forgotPassword() method to openGitHubPasswordResetPage() directly. The code is simple enough that it probably does not need to be wrapped in another method.

**Comment by EmilyYVChan** [comment]
I have acted on Chen's feedback to improve the code cohesion.

**Review by cli727 — APPROVED** [review]
Thanks for fixing the code. All good to go.

**Comment by cli727** [comment]
@softeng-701 Ready to merge

**Comment by softeng-701** [comment]
@EmilyYVChan @cli727 Please squash your commits

**Comment by EmilyYVChan** [comment]
@softeng-701 I've squashed the commits. :)

**Pull request merged**
