### PR TITLE
clone icon added to toolbar

### PR DESCRIPTION
**Pull request by kzy618**
Clone icon is added on the toolbar to facilitate user.
Clone icon will only display the clone information, but not the open repository
The icon is triggered with onclick function to switch to the clone panel.
Fixed error.

Closes issue #16

### CODE REVIEW

**Review by Mehdi-Shah — APPROVED** [review]
Looks fine to me

**Review by sahilcc7 — APPROVED** [review]
Code looks fine...

**Comment by kzy618** [comment]
@softeng-701

**Comment by softeng-701** [comment]
@kzy618 Looks good, will merge this after the deadline

**Comment by softeng-701** [comment]
@kzy618 This PR is for a closed issue, was it closed early?

**Comment by sahilcc7** [comment]
@softeng-701 Sorry I accidentally closed the issues before the pull request was merged in. I have reopened the issue. Cheers

**Pull request merged**
