### PR TITLE
Change name of repositories that were cloned from GitHub

### LINKED ISSUE #6: Change naming of repos cloned from GitHub
When you clone a repository from GitHub, the local folder which is created is named after the author’s name rather than the project’s name. This is especially a problem if you want to clone two repositories from the same author, as this will cause an error.

### PR DESCRIPTION
**Pull request by EmilyYVChan**
Closes #6 .

Before, the cloned repositories were named after the user's GitHub username. This prevents the user from cloning multiple repositories as they would be cloned to a directory of the same name. 

This bug was due to the variable 'localPath' storing the username, which was used to define the full directory address to which the repository is cloned to.

Changes made:
- extract the repository's name from the clone URL.
- append the extracted name to the full local directory path address
- for the git command shown to the user, remove the optional directory option. This is to ensure that the git command shown matches the git command executed.

### CODE REVIEW

**Review by cli727 — APPROVED** [review]
Looks good to me 👍

**Comment by cli727** [comment]
@softeng-701 Ready for merge

**Comment by softeng-701** [comment]
@EmilyYVChan Please squash your commits, thanks

**Comment by EmilyYVChan** [comment]
Apologies. I have discovered a bug at the last minute.
The bug is that the label in the header bar was still showing the user's GitHub username instead of the repository name. I have fixed this changes, but I am starting a new pull request to restart the reviewing procedure.

**Pull request closed without merging**
