### PR TITLE
Fixes Issue#51 - Commits are now not allowed when there is nothing to commit

### PR DESCRIPTION
**Pull request by Scoobster**
This pull request is for closing the Issue #51 : Commits are allowed when there is nothing to commit

Functionality Added:
Added a check after all the files that have been checked are located. So will throw an error if no files are checked. This is caught in the catch to then display a modal to alert the user not files were selected to commit.

Files changed:
- app/misc/git.js
- app/misc/git.ts

### CODE REVIEW

**Comment by softeng-701** [comment]
@Scoobster Please squash your commits. Also, remember to tag this account, so we get notified of your PR, thanks!

**Comment by Scoobster** [comment]
@softeng-701 I was waiting for teammate to approve before tagging. In regards to squashing commits, when I go to squash I get all the commits from Kelly's master since merging the branch to ensure no merge conflicts. See attached image as the only the top 2 commits are my own.
how one rebases

**Review by nathangavin — APPROVED** [review]
looks good, no changes are needed

**Comment by Scoobster** [comment]
@softeng-701 tagging now for merge. Please see above comment in regards to squashing commits

**Pull request merged**
